package:
    name: pygc
    version: "1.2.1"

source:
    path: ../

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy

test:
    imports:
        - pygc

about:
    home: https://github.com/axiom-data-science/pygc
    license: MIT License
    summary: Great Circle calculations for Python 2/3 using Vincenty's formulae
